module.exports = {
  apps: [
    {
      name: 'jinlee-web',
      cwd: '/www/wwwroot/jinleeWeb',
      script: 'npm',
      args: 'start -- --hostname 127.0.0.1 --port 3000',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
      },
    },
    {
      name: 'jinlee-monthly-financial-reports',
      cwd: '/www/wwwroot/jinleeWeb',
      script: 'scripts/monthly-financial-report-scheduler.mjs',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'production',
        REPORT_GENERATOR_URL: 'http://127.0.0.1:3000/api/admin/revenue/files/generate-due',
        REPORT_GENERATOR_TIME_ZONE: 'Europe/Rome',
      },
    },
    {
      name: 'jinlee-wechat-native-reconcile',
      cwd: '/www/wwwroot/jinleeWeb',
      script: 'scripts/wechat-native-reconcile-scheduler.mjs',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'production',
        WECHAT_NATIVE_RECONCILE_URL: 'http://127.0.0.1:3000/api/internal/wechat-native/reconcile',
        WECHAT_NATIVE_RECONCILE_INTERVAL_MS: '300000',
      },
    },
    {
      name: 'jinlee-auth-login-audit-retention',
      cwd: '/www/wwwroot/jinleeWeb',
      script: 'scripts/auth-login-audit-retention-scheduler.mjs',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'production',
        AUTH_LOGIN_AUDIT_PURGE_URL: 'http://127.0.0.1:3000/api/internal/auth-login-audit/purge',
        AUTH_LOGIN_AUDIT_PURGE_INTERVAL_MS: '86400000',
      },
    },
  ],
};
