CREATE TYPE "PeiwanSex" AS ENUM ('小姐姐','小哥哥');
CREATE TYPE "PeiwanType" AS ENUM ('大神陪玩','技术陪玩','娱乐陪玩');
CREATE TYPE "PeiwanLevel" AS ENUM ('优选陪玩','明星陪玩','殿堂陪玩');

ALTER TABLE "PEIWAN"
  ADD COLUMN "sex" "PeiwanSex" NOT NULL DEFAULT '小姐姐',
  ADD COLUMN "exclusive" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "type" "PeiwanType" NOT NULL DEFAULT '娱乐陪玩',
  ADD COLUMN "level" "PeiwanLevel" NOT NULL DEFAULT '优选陪玩',
  ADD COLUMN "LOL" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "CSGO" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "Valorant" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "Naraka" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "OW2" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "APEX" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "deltaForce" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "marvel" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "singer" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "PUBG" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "TFT" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "R6" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "tarkov" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "chat" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "steam" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "DOTA" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "COD" BOOLEAN NOT NULL DEFAULT false;
