ALTER TYPE "FarmActionType" ADD VALUE IF NOT EXISTS 'STEAL';

ALTER TABLE "FarmPlot"
  ADD COLUMN IF NOT EXISTS "lastStolenAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "lastStolenBy" TEXT,
  ADD COLUMN IF NOT EXISTS "stolenCoins" DECIMAL(19,4) NOT NULL DEFAULT 0;
