-- Set ON UPDATE CASCADE for PEIWANID references
ALTER TABLE "Order" DROP CONSTRAINT IF EXISTS "Order_peiwanId_fkey";
ALTER TABLE "Order"
  ADD CONSTRAINT "Order_peiwanId_fkey"
  FOREIGN KEY ("peiwanId") REFERENCES "PEIWAN"("PEIWANID")
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "PeiwanDeletion" DROP CONSTRAINT IF EXISTS "PeiwanDeletion_peiwanId_fkey";
ALTER TABLE "PeiwanDeletion"
  ADD CONSTRAINT "PeiwanDeletion_peiwanId_fkey"
  FOREIGN KEY ("peiwanId") REFERENCES "PEIWAN"("PEIWANID")
  ON DELETE CASCADE ON UPDATE CASCADE;
