ALTER TYPE "CouponType" ADD VALUE IF NOT EXISTS 'CROWN_DAY_95_VOUCHER';
ALTER TYPE "CouponType" ADD VALUE IF NOT EXISTS 'CROWN_DAY_92_VOUCHER';
ALTER TYPE "CouponType" ADD VALUE IF NOT EXISTS 'CROWN_3DAY_92_VOUCHER';
ALTER TYPE "CouponType" ADD VALUE IF NOT EXISTS 'CROWN_WEEK_92_VOUCHER';
ALTER TYPE "CouponType" ADD VALUE IF NOT EXISTS 'CROWN_MONTH_92_VOUCHER';
