// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/accounts/discord/login" | "/admin" | "/admin/cards/list" | "/admin/cards/recommend" | "/admin/gifts" | "/admin/migrate-discord" | "/admin/order-requests" | "/admin/peiwan/[discordId]" | "/admin/peiwan/new" | "/admin/referrals" | "/admin/refundable-gifts" | "/admin/transactions" | "/join" | "/peiwanList" | "/profile" | "/profile/bag" | "/profile/giftwall" | "/profile/heart" | "/recharge" | "/recharge/result"
type AppRouteHandlerRoutes = "/accounts/discord/login/callback" | "/api/admin/gifts" | "/api/admin/gifts/image" | "/api/admin/migrate-discord" | "/api/admin/peiwan" | "/api/admin/peiwan-cards/list" | "/api/admin/peiwan-cards/recommend" | "/api/admin/peiwan/[discordId]" | "/api/admin/referrals" | "/api/admin/referrals/[inviteeId]" | "/api/auth/callback/discord" | "/api/discord/login" | "/api/gift-wall" | "/api/logout" | "/api/lottery/use" | "/api/orders/[orderId]/discount" | "/api/orders/discountable" | "/api/payment/zpay/notify" | "/api/peiwan" | "/api/peiwanRecommend" | "/api/recharge/order" | "/api/recharge/order/[orderId]" | "/api/session" | "/api/voucher/use" | "/api/withdraw"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/accounts/discord/login": {}
  "/accounts/discord/login/callback": {}
  "/admin": {}
  "/admin/cards/list": {}
  "/admin/cards/recommend": {}
  "/admin/gifts": {}
  "/admin/migrate-discord": {}
  "/admin/order-requests": {}
  "/admin/peiwan/[discordId]": { "discordId": string; }
  "/admin/peiwan/new": {}
  "/admin/referrals": {}
  "/admin/refundable-gifts": {}
  "/admin/transactions": {}
  "/api/admin/gifts": {}
  "/api/admin/gifts/image": {}
  "/api/admin/migrate-discord": {}
  "/api/admin/peiwan": {}
  "/api/admin/peiwan-cards/list": {}
  "/api/admin/peiwan-cards/recommend": {}
  "/api/admin/peiwan/[discordId]": { "discordId": string; }
  "/api/admin/referrals": {}
  "/api/admin/referrals/[inviteeId]": { "inviteeId": string; }
  "/api/auth/callback/discord": {}
  "/api/discord/login": {}
  "/api/gift-wall": {}
  "/api/logout": {}
  "/api/lottery/use": {}
  "/api/orders/[orderId]/discount": { "orderId": string; }
  "/api/orders/discountable": {}
  "/api/payment/zpay/notify": {}
  "/api/peiwan": {}
  "/api/peiwanRecommend": {}
  "/api/recharge/order": {}
  "/api/recharge/order/[orderId]": { "orderId": string; }
  "/api/session": {}
  "/api/voucher/use": {}
  "/api/withdraw": {}
  "/join": {}
  "/peiwanList": {}
  "/profile": {}
  "/profile/bag": {}
  "/profile/giftwall": {}
  "/profile/heart": {}
  "/recharge": {}
  "/recharge/result": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
