// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/accounts/discord/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/discord/login">> = Specific
  const handler = {} as typeof import("../../app/accounts/discord/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/cards/list/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cards/list">> = Specific
  const handler = {} as typeof import("../../app/admin/cards/list/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/cards/recommend/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cards/recommend">> = Specific
  const handler = {} as typeof import("../../app/admin/cards/recommend/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/gifts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/gifts">> = Specific
  const handler = {} as typeof import("../../app/admin/gifts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/migrate-discord/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/migrate-discord">> = Specific
  const handler = {} as typeof import("../../app/admin/migrate-discord/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/order-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/order-requests">> = Specific
  const handler = {} as typeof import("../../app/admin/order-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/peiwan/[discordId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/peiwan/[discordId]">> = Specific
  const handler = {} as typeof import("../../app/admin/peiwan/[discordId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/peiwan/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/peiwan/new">> = Specific
  const handler = {} as typeof import("../../app/admin/peiwan/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/referrals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/referrals">> = Specific
  const handler = {} as typeof import("../../app/admin/referrals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/refundable-gifts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/refundable-gifts">> = Specific
  const handler = {} as typeof import("../../app/admin/refundable-gifts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/transactions">> = Specific
  const handler = {} as typeof import("../../app/admin/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/join/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/join">> = Specific
  const handler = {} as typeof import("../../app/join/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/peiwanList/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/peiwanList">> = Specific
  const handler = {} as typeof import("../../app/peiwanList/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/bag/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/bag">> = Specific
  const handler = {} as typeof import("../../app/profile/bag/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/giftwall/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/giftwall">> = Specific
  const handler = {} as typeof import("../../app/profile/giftwall/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/heart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/heart">> = Specific
  const handler = {} as typeof import("../../app/profile/heart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recharge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recharge">> = Specific
  const handler = {} as typeof import("../../app/recharge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recharge/result/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recharge/result">> = Specific
  const handler = {} as typeof import("../../app/recharge/result/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/accounts/discord/login/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/accounts/discord/login/callback">> = Specific
  const handler = {} as typeof import("../../app/accounts/discord/login/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/gifts/image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/gifts/image">> = Specific
  const handler = {} as typeof import("../../app/api/admin/gifts/image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/gifts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/gifts">> = Specific
  const handler = {} as typeof import("../../app/api/admin/gifts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/migrate-discord/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/migrate-discord">> = Specific
  const handler = {} as typeof import("../../app/api/admin/migrate-discord/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/peiwan-cards/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/peiwan-cards/list">> = Specific
  const handler = {} as typeof import("../../app/api/admin/peiwan-cards/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/peiwan-cards/recommend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/peiwan-cards/recommend">> = Specific
  const handler = {} as typeof import("../../app/api/admin/peiwan-cards/recommend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/peiwan/[discordId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/peiwan/[discordId]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/peiwan/[discordId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/peiwan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/peiwan">> = Specific
  const handler = {} as typeof import("../../app/api/admin/peiwan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/referrals/[inviteeId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/referrals/[inviteeId]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/referrals/[inviteeId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/referrals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/referrals">> = Specific
  const handler = {} as typeof import("../../app/api/admin/referrals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/callback/discord/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/callback/discord">> = Specific
  const handler = {} as typeof import("../../app/api/auth/callback/discord/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/discord/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discord/login">> = Specific
  const handler = {} as typeof import("../../app/api/discord/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gift-wall/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gift-wall">> = Specific
  const handler = {} as typeof import("../../app/api/gift-wall/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/logout">> = Specific
  const handler = {} as typeof import("../../app/api/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/lottery/use/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lottery/use">> = Specific
  const handler = {} as typeof import("../../app/api/lottery/use/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/[orderId]/discount/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[orderId]/discount">> = Specific
  const handler = {} as typeof import("../../app/api/orders/[orderId]/discount/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/discountable/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/discountable">> = Specific
  const handler = {} as typeof import("../../app/api/orders/discountable/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/payment/zpay/notify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/zpay/notify">> = Specific
  const handler = {} as typeof import("../../app/api/payment/zpay/notify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/peiwan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/peiwan">> = Specific
  const handler = {} as typeof import("../../app/api/peiwan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/peiwanRecommend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/peiwanRecommend">> = Specific
  const handler = {} as typeof import("../../app/api/peiwanRecommend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/recharge/order/[orderId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recharge/order/[orderId]">> = Specific
  const handler = {} as typeof import("../../app/api/recharge/order/[orderId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/recharge/order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recharge/order">> = Specific
  const handler = {} as typeof import("../../app/api/recharge/order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/session">> = Specific
  const handler = {} as typeof import("../../app/api/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/voucher/use/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voucher/use">> = Specific
  const handler = {} as typeof import("../../app/api/voucher/use/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/withdraw/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/withdraw">> = Specific
  const handler = {} as typeof import("../../app/api/withdraw/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
